### ISSUE TITLE
Webservice Integration

### ISSUE THREAD

**Issue by vstman** [rubygarage/react-native-firebase-chat#3]
Hi friends,
I want to obtain information from you. I made a chat app with firebase and it is working correctly. But i want to use my web services and mysql database for save datas also at this point.  Do you have any suggestion about this? 
Thanks all.

**Comment by plzen** [comment]
Hello @vstman,

1. If you want to use your own backend with app, you need to rewrite `FirebaseService` and to change actions to use your endpoints.
2. You can try Firebase Functions. Create webhook for database writes and send additional requests to you web service. In this case you will be able to use both Firebase and your web service. More details here https://github.com/firebase/functions-samples/tree/master/minimal-webhook

**Comment by vstman** [comment]
Thanks @plzen . I will try .

**Comment by vstman** [comment]
Hello @plzen,

I want to ask one more thing. In existing system; two or there or more user can access channel on same time. But i want to make this channel just for two user. How can i do it with channel id? Just i want to make a chat who has the channel id he can access this channel id's channel.

**Comment by plzen** [comment]
You need to reorganize database and create relation between chats and users.

For example, you can create path for storing chats (instead of messages as currently implemented) and for each chat create property `users` with list of users belongs to this chat. The same thing you need to store messages for chat.

After that select chats which related to logged in user and display it in the app. Store all new messages in chat property `messages` and add new users to chat to `users`.
